url: "https://alandefreitas.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/alandefreitas" # the subpath of your site, e.g. /blog
title: "Alan de Freitas" # the name of your site, e.g. ACME Corp.
description: "A small website to share my stuff"
